name: Image Conversion Trigger

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'file_to_convert/*.jpg'
      - 'file_to_convert/*.jpeg'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::943755888375:role/
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          FILE=$(git diff --name-only HEAD^ HEAD | grep 'file_to_convert/' | head -n 1)
          if [ -z "$FILE" ]; then exit 0; fi
          
          FILENAME=$(basename "$FILE" | cut -d. -f1)
          EXTENSION="${FILE##*.}"
          DATE=$(date +%m-%d-%Y)
          NEW_NAME="${FILENAME}_${DATE}.${EXTENSION}"
          
          aws s3 cp "$FILE" "s3://image-convert-erraw/$NEW_NAME"